name: Publish package to GitHub Packages
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup version
        run: echo "::set-output name=AP_VERSION::${GITHUB_REF##*/}"
      - name: Publish package
        run: mvn --batch-mode deploy && mkdir -p target/${AP_VERSION} && cp target/*.jar target/${AP_VERSION}/.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/${AP_VERSION}
